@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNjM5NzA1ODY4fQ.oRQd27REhETZxO34uCxNhWckGKiWKZ46ImbZe9BbkBU


# USER ACTIONS

# USER SESSION

### Sessions Create
POST http://localhost:3000/sessions
Authorization: Bearer{{jwt}}
Content-Type: application/json

{
  "email": "bob@burgers.com",
  "password": "password"
  
}

### User Create
POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name" : "Gene",
  "last_name" : "Belcher",
  "email": "gene@burgers.com",
  "password": "password",
  "password_confirmation": "password"
}

### User Destroy
DELETE http://localhost:3000/users/7
Authorization: Bearer{{jwt}}


# ITEM ACTIONS

### Item Create
POST http://localhost:3000/items
Authorization: Bearer{{jwt}}
Content-Type: application/json

{
  "item_title": "Studio 54",
  "category_id": "4"
}

### Items Index
GET http://localhost:3000/items
Authorization: Bearer{{jwt}}

### Item Show
GET http://localhost:3000/items/7
Authorization: Bearer{{jwt}}

# CATEGORY ACTIONS  
### Create
POST http://localhost:3000/categories
Authorization: Bearer{{jwt}}
Content-Type: application/json

{
  "category_title": "Places to Perform",
  "user_id": 6
}

### Show
GET http://localhost:3000/categories/5
Authorization: Bearer{{jwt}}

### Index
GET http://localhost:3000/categories



# NOTES ACTIONS  
### Create
POST http://localhost:3000/notes
Authorization: Bearer{{jwt}}
Content-Type: application/json

{
  "description": "Go back in time and perform stand up comedy at Studio 54 for Austin Powers and his Faja.",
  "item_id": 7
}

### Show
GET http://localhost:3000/notes/4
Authorization: Bearer{{jwt}}

# IMAGE ACTIONS

### Create
POST http://localhost:3000/images
Authorization: Bearer{{jwt}}
Content-Type: application/json

{
  "url": "https://www.magneticmag.com/.image/t_share/MTUwMDA1NDY1OTQ0Njk2NjAy/studio-54-disco.jpg",
  "item_id": 4
}

### Show
GET http://localhost:3000/images/3
Authorization: Bearer{{jwt}}


# SOCIAL POST ACTIONS

### Create
POST http://localhost:3000/social_posts
Authorization: Bearer{{jwt}}
Content-Type: application/json

{
  "url": "https://twitter.com/studio54music",
  "item_id": 7
}

### Show
GET http://localhost:3000/social_posts/2
Authorization: Bearer{{jwt}}