@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNjM5NjE3NTI5fQ.zXGXcyx28Yx82X6WT1r9ojcQMmdE77qThIbv7BQ5-FA


# USER ACTIONS

# USER SESSION

### Sessions Create
POST http://localhost:3000/sessions
Authorization: Bearer{{jwt}}
Content-Type: application/json

{
  "email": "bob@burgers.com",
  "password": "password"
  
}

### User Create
POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name" : "Gene",
  "last_name" : "Belcher",
  "email": "gene@burgers.com",
  "password": "password",
  "password_confirmation": "password"
}

### User Destroy
DELETE http://localhost:3000/users/7


# ITEM ACTIONS

### Item Create
POST http://localhost:3000/items
Content-Type: application/json

{
  "item_title": "Studio 54",
  "category_id": "4"
}

### Item Show
GET http://localhost:3000/items/7

# CATEGORY ACTIONS  
### Create
POST http://localhost:3000/categories
Content-Type: application/json

{
  "category_title": "Places to Perform",
  "user_id": 6
}

### Show
GET http://localhost:3000/categories/4

### Index
GET http://localhost:3000/categories
Authorization: Bearer{{jwt}}


# NOTES ACTIONS  
### Create
POST http://localhost:3000/notes
Content-Type: application/json

{
  "description": "Go back in time and perform stand up comedy at Studio 54 for Austin Powers and his Faja.",
  "item_id": 7
}

### Show
GET http://localhost:3000/notes/4


# IMAGE ACTIONS

### Create
POST http://localhost:3000/images
Content-Type: application/json

{
  "url": "https://www.magneticmag.com/.image/t_share/MTUwMDA1NDY1OTQ0Njk2NjAy/studio-54-disco.jpg",
  "item_id": 4
}

### Show
GET http://localhost:3000/images/3


# SOCIAL POST ACTIONS

### Create
POST http://localhost:3000/social_posts
Content-Type: application/json

{
  "url": "https://twitter.com/studio54music",
  "item_id": 7
}

### Show
GET http://localhost:3000/social_posts/2